# Grouped CRDC Data Columns needed for analysis

MULTIPLE_SUSPENSIONS = [
'SCH_DISCWODIS_MULTOOS_HI_M',
'SCH_DISCWODIS_MULTOOS_HI_F',
'SCH_DISCWODIS_MULTOOS_BL_M',
'SCH_DISCWODIS_MULTOOS_BL_F',
'SCH_DISCWODIS_MULTOOS_WH_M',
'SCH_DISCWODIS_MULTOOS_WH_F',
'TOT_DISCWODIS_MULTOOS_M',
'TOT_DISCWODIS_MULTOOS_F']

# Overal demographics at schools
DEMOGRAPHIC_COUNT_COLS = [
    'SCH_ENR_HI_M',
    'SCH_ENR_HI_F',
    'SCH_ENR_BL_M',
    'SCH_ENR_BL_F',
    'SCH_ENR_WH_M',
    'SCH_ENR_WH_F',
    'TOT_ENR_M',
    'TOT_ENR_F'
]

# Expulsion
EXPULSION_ZERO_TOLERANCE = [
'SCH_DISCWODIS_EXPZT_HI_M',
'SCH_DISCWODIS_EXPZT_HI_F',
'SCH_DISCWODIS_EXPZT_BL_M',
'SCH_DISCWODIS_EXPZT_BL_F',
'SCH_DISCWODIS_EXPZT_WH_M',
'SCH_DISCWODIS_EXPZT_WH_F',
'TOT_DISCWODIS_EXPZT_F',
'TOT_DISCWODIS_EXPZT_M']

EXPULSION_WO_ED = [
'SCH_DISCWODIS_EXPWOE_HI_M',
'SCH_DISCWODIS_EXPWOE_HI_F',
'SCH_DISCWODIS_EXPWOE_BL_M',
'SCH_DISCWODIS_EXPWOE_BL_F',
'SCH_DISCWODIS_EXPWOE_WH_M',
'SCH_DISCWODIS_EXPWOE_WH_F',
'TOT_DISCWODIS_EXPWOE_F',
'TOT_DISCWODIS_EXPWOE_M']

EXPULSION_W_ED = [
'SCH_DISCWODIS_EXPWE_HI_M',
'SCH_DISCWODIS_EXPWE_HI_F',
'SCH_DISCWODIS_EXPWE_BL_M',
'SCH_DISCWODIS_EXPWE_BL_F',
'SCH_DISCWODIS_EXPWE_WH_M',
'SCH_DISCWODIS_EXPWE_WH_F',
'TOT_DISCWODIS_EXPWE_F',
'TOT_DISCWODIS_EXPWE_M']

# Officers, counselors
COUNSELOR_STAFF = ['SCH_FTESERVICES_NUR', 'SCH_FTESERVICES_PSY','SCH_FTESERVICES_SOC']
SECURITY_STAFF = ['SCH_FTESECURITY_LEO', 'SCH_FTESECURITY_GUA']

JUSTICE_FACILITY = ['SCH_JJTYPE']

SCHOOL_INFO_COLS = ['SCH_NAME', 'LEA_STATE_NAME', 'LAT1516', 'LON1516']

cols_of_interest = []
cols_of_interest += MULTIPLE_SUSPENSIONS
cols_of_interest += DEMOGRAPHIC_COUNT_COLS 
cols_of_interest += EXPULSION_ZERO_TOLERANCE + EXPULSION_W_ED + EXPULSION_WO_ED
cols_of_interest += COUNSELOR_STAFF + SECURITY_STAFF + JUSTICE_FACILITY + SCHOOL_INFO_COLS

COLS_WITH_NEEDED_DATA = cols_of_interest
